### ISSUE TITLE
Add support for The Witcher 3: Wild Hunt

### ISSUE THREAD

**Issue by KerberX** [KerberX/Kortex-Mod-Manager#11]
# Description
Add support for **The Witcher 3: Wild Hunt**, as requested by @Project579. This kind of related to #10, but support for Witcher 3 may require another plugin manager implementation and some other things rendering it impossible to provide support with just template instance.

# Tasks
- [ ] Research Witcher 3 mods system
- [ ] Create new plugin manager implementation if needed.
- [ ] Create instance template.

**Comment by Project579** [comment]
Looking Forward to it!
