### ISSUE TITLE
General enhancement list

### ISSUE THREAD

**Issue by KerberX** [KerberX/Kortex-Mod-Manager#2]
## This is the list of planned improvements
They are not tied to any particular release. I will work on them when it's would be a good time to implement them.

When another release is ready some of them will be moved to their own issue and assigned to milestone.

# So, the list
- [ ] Mod lists backup functionality.
- [ ] Add user definable game templates.
- [ ] Support for BAIN.
- [ ] Support for OMOD.
- [ ] Maybe add option to generate fully NMM and MO compatible FOMod when really complex requirements configuration is present.
- [ ] Drag-and-move image in image viewer.
- [ ] Allow file operations on currently selected file in packages list.
- [ ] Test network function when no internet connection available.
- [ ] New app settings window UI. Right now it uses KConfigManager UI.
- [ ] Web functions for known providers.
  - [x] NexusMods
  - [ ] LoversLab
  - [ ] TESALL.RU

**Comment by KerberX** [comment]
Settings window using new ConfigManager backend and UI is done.
