### ISSUE TITLE
Rework About dialog

### ISSUE THREAD

**Issue by KerberX** [KerberX/Kortex-Mod-Manager#7]
# Description
With added license and opening the source about dialog need to be changed.

# Tasks
- [x] Create separate tab for used libraries and tools. Include license for every library.
- [x] Remove unwanted entries from **Modules** tab and put in order module versioning. Most of entries there don't need their own version.
- [x] Replace **Permissions** tab by **License** tab,

**Comment by KerberX** [comment]
Done. Dialog might need tome minor changes in the future, but generally it's finished.
https://cdn.discordapp.com/attachments/455116957658775564/529539011182723102/1.png
https://cdn.discordapp.com/attachments/455116957658775564/529539021223886850/2.png
