### ISSUE TITLE
Allow install engine use Kortex environment variables 

### ISSUE THREAD

**Issue by KerberX** [KerberX/Kortex-Mod-Manager#9]
# Description
All variables that install engine could use is created by package author with exception of requirement group variables which is automatic (though requirement groups is created by package author).

I can see some benefits in allowing to use environment variables to create conditional install that depends not only on installer and requirements state, but also on system state.

# Tasks
- [ ] Allow install engine recognize and check environment variables.
- [ ] Add window to select environment variable from their list instead of typing it by hand.
- [ ] Write Wiki article about Kortex environment variables.
